name: Tests

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name, 'docs only')
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "macos-latest"]
        numpy-version: ["latest"]
        gala-nogsl: ["0"]
        pip-additional: [""]
        include:

          - name: Oldest numpy version supported
            os: ubuntu-latest
            python-version: "3.11"
            numpy-version: "1.24"
            gala-nogsl: "0"
            pip-additional: ""

          - name: Install without GSL
            os: ubuntu-latest
            python-version: "3.11"
            numpy-version: "latest"
            gala-nogsl: "1"
            pip-additional: ""

          - name: With optional dependencies
            os: ubuntu-latest  # note: galpy install failed on macos here
            python-version: "3.11"
            numpy-version: "latest"
            gala-nogsl: "1"
            pip-additional: "extra"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      # For animation tests
      - uses: FedericoCarboni/setup-ffmpeg@v3
        if: ${{ !startsWith(matrix.os, 'mac') }}
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          github-token: ${{ secrets.GITHUB_TOKEN }}
        id: setup-ffmpeg

      # Mac:
      - name: Setup Mac - GSL
        if: startsWith(matrix.os, 'mac')
        run: |
          brew install gsl

      # Ubuntu:
      - name: Setup Linux - GSL
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install gsl-bin libgsl0-dev build-essential
          sudo apt-get install libhdf5-serial-dev  # TODO: remove when h5py has 3.11 wheels

      - name: Install package and dependencies
        run: python -m pip install .[test ${{ matrix.pip-additional }}]
        env:
          GALA_NOGSL: ${{ matrix.gala-nogsl }}

      - name: Update versions if testing min versions
        if: matrix.numpy-version != 'latest'
        run: |
          python -m pip install numpy~=${{ matrix.numpy-version }}

      - name: Run tests
        run: >-
          python -m pytest -ra --cov --cov-report=xml --cov-report=term
          --durations=20

      - name: Upload coverage report
        uses: codecov/codecov-action@v4.5.0
